# Generated by Django 4.2.5 on 2023-09-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingparser',
            options={'verbose_name': 'Парсер рейтинга', 'verbose_name_plural': 'Парсеры рейтинга'},
        ),
        migrations.AlterModelOptions(
            name='reviewsparser',
            options={'verbose_name': 'Парсер отзывов', 'verbose_name_plural': 'Парсеры отзывов'},
        ),
    ]
