# Generated by Django 4.2.5 on 2023-10-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0023_alter_websitecard_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=255, verbose_name='ID пользователя telegram')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.branch', verbose_name='филиал')),
            ],
            options={
                'verbose_name': 'telegram подписка на оповещения',
                'verbose_name_plural': 'telegram подписки на оповещения',
                'db_table': 'webhook_telegram_subscription',
            },
        ),
    ]
