# Generated by Django 4.2.5 on 2023-10-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_alter_branch_api_secret'),
        ('webhooks', '0003_alter_telegramsubscription_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegramsubscription',
            unique_together={('telegram_user_id', 'branch')},
        ),
    ]
