# Generated by Django 4.2.5 on 2023-09-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0002_negativereview_branch'),
        ('resources', '0006_websitepage_website'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('negative_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.negativereview')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeMessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('negative_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.negativemessage')),
            ],
        ),
    ]
