# Generated by Django 4.2.5 on 2023-09-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negativemessageevent',
            options={'verbose_name': 'Сообытие негативного сообщения', 'verbose_name_plural': 'Сообытия негативного сообщения'},
        ),
        migrations.AlterModelOptions(
            name='negativereviewevent',
            options={'verbose_name': 'Сообытие негативного отзыва', 'verbose_name_plural': 'Сообытия негативного отзыва'},
        ),
    ]
