# Generated by Django 4.2.5 on 2023-09-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name': 'Сообщение на почту', 'verbose_name_plural': 'Сообщения на почту'},
        ),
        migrations.AlterModelOptions(
            name='phonemessage',
            options={'verbose_name': 'Сообщение на телефон', 'verbose_name_plural': 'Сообщения на телефон'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'verbose_name': 'Сообщение на telegram', 'verbose_name_plural': 'Сообщения на telegram'},
        ),
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'verbose_name': 'Сообщение на whatsapp', 'verbose_name_plural': 'Сообщения на whatsapp'},
        ),
    ]
