# Generated by Django 4.2.5 on 2023-09-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_websitepage_website'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativereview',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.branch'),
            preserve_default=False,
        ),
    ]
