# Generated by Django 4.2.5 on 2023-09-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_websitepage_website'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feedback', '0002_negativereview_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negativemessage',
            options={'verbose_name': 'Негативное сообщение', 'verbose_name_plural': 'Негативные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='negativereview',
            options={'verbose_name': 'Негативный отзыв', 'verbose_name_plural': 'Негативные отзывы'},
        ),
        migrations.CreateModel(
            name='PositiveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('text', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Позитивный отзыв',
                'verbose_name_plural': 'Позитивные отзывы',
            },
        ),
    ]
