# Generated by Django 4.2.5 on 2023-10-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_negativemessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negativemessage',
            name='name',
        ),
        migrations.AlterField(
            model_name='negativemessage',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='negativemessage',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterModelTable(
            name='negativemessage',
            table='feedback_negative_message',
        ),
        migrations.AlterModelTable(
            name='negativereview',
            table='feedback_negative_review',
        ),
        migrations.AlterModelTable(
            name='positivereview',
            table='feedback_positive_review',
        ),
    ]
