# Generated by Django 4.2.5 on 2023-10-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_alter_websitecard_platform'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feedback', '0004_remove_negativemessage_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negativemessage',
            options={'verbose_name': 'негативное сообщение', 'verbose_name_plural': 'негативные сообщения'},
        ),
        migrations.AlterField(
            model_name='negativemessage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch', verbose_name='филиал'),
        ),
        migrations.AlterField(
            model_name='negativemessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='группа'),
        ),
    ]
