# Generated by Django 4.2.5 on 2023-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_negativemessagetag_alter_negativereview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:01:00'),
            preserve_default=False,
        ),
    ]
