# Generated by Django 4.2.5 on 2023-10-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_negativemessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negativemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
