from django.urls import path

from .views import (
    account,
    billing,
    CompanyCreateView,
    CompanyContactUpdateView,
    CompanyDataUpdateView,
    CompanyDetailView,
    CompanyListView,
    CompanyLinkUpdateView,
    CompanyParserUpdateView,
    CompanyRatingYandexDynamic,
    CompanyRatingGisDynamic,
    CompanyRatingGoogleDynamic,
    MessageListView,
    profile,
    qr,
    rate,
    ReviewListView,
    ReviewUpdateView,
    security,
    telegram_notify_unsubscribe,
    user_create,
    user_login,
    user_logout,
    widget_rating,
    widget_reviews
)

urlpatterns = [
    path("", CompanyListView.as_view(), name="company_list"),
    path("company/create/", CompanyCreateView.as_view(), name="company_create"),
    path("company/<int:pk>/", CompanyDetailView.as_view(), name="company_detail"),
    path("company/<int:pk>/parser_update/", CompanyParserUpdateView.as_view(), name="company_parser_update"),
    path("company/<int:pk>/data_update/", CompanyDataUpdateView.as_view(), name="company_data_update"),
    path("company/<int:pk>/link_update/", CompanyLinkUpdateView.as_view(), name="company_link_update"),
    path("company/<int:pk>/contact_update/", CompanyContactUpdateView.as_view(), name="company_contact_update"),
    path("company/<int:company_pk>/rating_yandex_dynamic/", CompanyRatingYandexDynamic.as_view(), name="company_rating_yandex_dynamic"),
    path("company/<int:company_pk>/rating_gis_dynamic/", CompanyRatingGisDynamic.as_view(), name="company_rating_gis_dynamic"),
    path("company/<int:company_pk>/rating_google_dynamic/", CompanyRatingGoogleDynamic.as_view(), name="company_rating_google_dynamic"),
    path("company/<int:company_pk>/review/", ReviewListView.as_view(), name="review_list"),
    path("company/<int:company_pk>/review/<int:pk>/update/", ReviewUpdateView.as_view(), name="review_update"),
    path("company/<int:company_pk>/message/", MessageListView.as_view(), name="message_list"),
    path("company/<int:company_pk>/qr/", qr, name="qr"),
    path("company/<int:company_pk>/widget_rating/", widget_rating, name="widget_rating"),
    path("company/<int:company_pk>/widget_reviews/", widget_reviews, name="widget_reviews"),
    path("telegram_notify_unsubscribe/", telegram_notify_unsubscribe, name="telegram_notify_unsubscribe"),
    path("profile/", profile, name="profile"),
    path("rate/", rate, name="rate"),
    path("billing/", billing, name="billing"),
    path("account/", account, name="account"),
    path("security/", security, name="security"),
    path("create/", user_create, name="user_create"),
    path("login/", user_login, name="user_login"),
    path("logout/", user_logout, name="user_logout")
]
