from django.urls import path

from .views import (
    CompanyDetailView,
    CompanyListView,
    CompanyUpdateLinkYandexView,
    CompanyUpdateLinkGisView,
    CompanyUpdateLinkGoogleView,
    CompanyUpdateLinkAvitoView,
    CompanyUpdateLinkZoonView,
    CompanyUpdateLinkFlampView,
    CompanyUpdateLinkYellView,
    CompanyUpdateLinkOtzovikView,
    CompanyUpdateLinkIrecommendView,
    CompanyUpdateLinkProdoctorovView,
    CompanyUpdateLinkYandexServicesView,
    CompanyUpdateLinkTripadvisorView,
    CompanyUpdateFeedbackDataView,
    CompanyUpdateFeedbackContactView,
    CompanyUpdateFeedbackServiceView,
    CompanyUpdateWidgetView,
    MasterCompanyCreateView,
    MasterSearchGisView,
    MasterSearchGoogleView,
    MasterSearchYandexView,
    MembershipUpdateView,
    MessageListView,
    ProfileUpdateView,
    qr,
    ReviewListView,
    ReviewUpdateView,
    PasswordUpdateView,
    subscription,
    UserCreateView,
    UserLoginView,
    UserLogoutView,
    UserUpdateView,
)

urlpatterns = [
    path("", CompanyListView.as_view(), name="company_list"),
    path("company/<int:pk>/", CompanyDetailView.as_view(), name="company_detail"),
    path("company/<int:pk>/update_link_yandex/", CompanyUpdateLinkYandexView.as_view(), name="company_update_link_yandex"),
    path("company/<int:pk>/update_link_gis/", CompanyUpdateLinkGisView.as_view(), name="company_update_link_gis"),
    path("company/<int:pk>/update_link_google/", CompanyUpdateLinkGoogleView.as_view(), name="company_update_link_google"),
    path("company/<int:pk>/update_link_avito/", CompanyUpdateLinkAvitoView.as_view(), name="company_update_link_avito"),
    path("company/<int:pk>/update_link_zoon/", CompanyUpdateLinkZoonView.as_view(), name="company_update_link_zoon"),
    path("company/<int:pk>/update_link_flamp/", CompanyUpdateLinkFlampView.as_view(), name="company_update_link_flamp"),
    path("company/<int:pk>/update_link_yell/", CompanyUpdateLinkYellView.as_view(), name="company_update_link_yell"),
    path("company/<int:pk>/update_link_otzovik/", CompanyUpdateLinkOtzovikView.as_view(), name="company_update_link_otzovik"),
    path("company/<int:pk>/update_link_irecommend/", CompanyUpdateLinkIrecommendView.as_view(), name="company_update_link_irecommend"),
    path("company/<int:pk>/update_link_prodoctorov/", CompanyUpdateLinkProdoctorovView.as_view(), name="company_update_link_prodoctorov"),
    path("company/<int:pk>/update_link_yandex_services/", CompanyUpdateLinkYandexServicesView.as_view(), name="company_update_link_yandex_services"),
    path("company/<int:pk>/update_link_tripadvisor/", CompanyUpdateLinkTripadvisorView.as_view(), name="company_update_link_tripadvisor"),
    path("company/<int:pk>/update_feedback_data/", CompanyUpdateFeedbackDataView.as_view(), name="company_update_feedback_data"),
    path("company/<int:pk>/update_feedback_contact/", CompanyUpdateFeedbackContactView.as_view(), name="company_update_feedback_contact"),
    path("company/<int:pk>/update_feedback_service/", CompanyUpdateFeedbackServiceView.as_view(), name="company_update_feedback_service"),
    path("company/master/yandex/", MasterSearchYandexView.as_view(), name="master_search_yandex"),
    path("company/master/gis/", MasterSearchGisView.as_view(), name="master_search_gis"),
    path("company/master/google/", MasterSearchGoogleView.as_view(), name="master_search_google"),
    path("company/master/create/", MasterCompanyCreateView.as_view(), name="master_company_create"),
    path("company/<int:pk>/membership/update/", MembershipUpdateView.as_view(), name="membership_update"),
    path("company/<int:company_pk>/message/", MessageListView.as_view(), name="message_list"),
    path("password/update/", PasswordUpdateView.as_view(), name="password_update"),
    path("profile/update/", ProfileUpdateView.as_view(), name="profile_update"),

    # @TODO
    path("company/<int:company_pk>/qr/", qr, name="qr"),

    path("company/<int:company_pk>/review/", ReviewListView.as_view(), name="review_list"),
    path("company/<int:company_pk>/review/<int:pk>/update/", ReviewUpdateView.as_view(), name="review_update"),

    # @TODO
    path("subscription/", subscription, name="subscription"),

    path("user/create/", UserCreateView.as_view(), name="user_create"),
    path("user/update/", UserUpdateView.as_view(), name="user_update"),
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", UserLogoutView.as_view(), name="user_logout"),
    path("company/<int:pk>/update_widget/", CompanyUpdateWidgetView.as_view(), name="company_update_widget")
]
