# Generated by Django 4.2.5 on 2023-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_notify_at_end',
            field=models.TimeField(blank=True, null=True, verbose_name='можно оповещать до'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_notify_at_start',
            field=models.TimeField(blank=True, null=True, verbose_name='можно оповещать с'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_timezone',
            field=models.CharField(blank=True, choices=[('UTC', 'UTC')], default='UTC', null=True, verbose_name='Временная зона по умолчанию'),
        ),
    ]
