# Generated by Django 4.2.5 on 2023-10-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, verbose_name='ID telegram'),
        ),
    ]
