# Generated by Django 4.2.5 on 2023-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_profile_can_notify_at_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_notify_negative_gis',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='получать оповещения в Telegram о негативных отзывах в 2Гис Карты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_notify_negative_google',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='получать оповещения в Telegram о негативных отзывах в Google Maps'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_notify_negative_portrate',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='получать оповещения в Telegram о негативных сообщениях в Портрет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_notify_negative_yandex',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='получать оповещения в Telegram о негативных отзывах в Яндекс Карты'),
        ),
    ]
