# Generated by Django 4.2.5 on 2023-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, null=True, verbose_name='telegram ID'),
        ),
    ]
