# Generated by Django 4.2.5 on 2023-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_alter_profile_can_notify_at_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_notify_negative_mapsme',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='получать оповещения в Telegram о негативных отзывах в Mapsme'),
        ),
    ]
