# Generated by Django 5.0.1 on 2024-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_profile_can_notify_negative_mapsme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Europe/Moscow', 'Europe/Moscow'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg')], default='UTC', verbose_name='Временная зона по умолчанию'),
        ),
    ]
