# Generated by Django 5.0.1 on 2024-02-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0008_alter_profile_default_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Europe/Moscow', 'Москва'), ('Asia/Yekaterinburg', 'Екатеринбург')], default='UTC', verbose_name='Временная зона по умолчанию'),
        ),
    ]
