# Generated by Django 5.0.1 on 2024-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0009_alter_profile_default_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_secret',
            field=models.CharField(db_index=True, verbose_name='API ключ'),
        ),
    ]
