# Generated by Django 5.0.2 on 2024-03-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_alter_profile_api_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_notify_negative_mapsme',
        ),
    ]
