# Generated by Django 5.0.2 on 2024-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0011_remove_profile_can_notify_negative_mapsme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_notify_negative_gis',
            field=models.BooleanField(default=True, verbose_name='получать оповещения в Telegram о негативных отзывах в 2Гис Карты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_notify_negative_google',
            field=models.BooleanField(default=True, verbose_name='получать оповещения в Telegram о негативных отзывах в Google Maps'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_notify_negative_portrate',
            field=models.BooleanField(default=True, verbose_name='получать оповещения в Telegram о негативных сообщениях в Портрет'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_notify_negative_yandex',
            field=models.BooleanField(default=True, verbose_name='получать оповещения в Telegram о негативных отзывах в Яндекс Карты'),
        ),
    ]
