# Generated by Django 5.0.2 on 2024-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0012_alter_profile_can_notify_negative_gis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='can_notify_negative_portrate',
            field=models.BooleanField(default=True, verbose_name='получать оповещения в Telegram о сообщениях в Портрет'),
        ),
    ]
