# Generated by Django 4.2.5 on 2023-09-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitrix24integration',
            options={'verbose_name': 'Интеграция с Bitrix24', 'verbose_name_plural': 'Интеграции с Bitrix24'},
        ),
        migrations.AlterModelOptions(
            name='iikointegration',
            options={'verbose_name': 'Интеграция с Iiko Cloud', 'verbose_name_plural': 'Интеграции с Iiko Cloud'},
        ),
        migrations.AlterModelOptions(
            name='linkintegration',
            options={'verbose_name': 'Интеграция с файлом', 'verbose_name_plural': 'Интеграции с файлом'},
        ),
        migrations.AlterModelOptions(
            name='topnlabintegration',
            options={'verbose_name': 'Интеграция с Topnlab', 'verbose_name_plural': 'Интеграции с Topnlab'},
        ),
        migrations.AlterModelOptions(
            name='yclientsintegration',
            options={'verbose_name': 'Интеграция с Yclients', 'verbose_name_plural': 'Интеграции с Yclients'},
        ),
    ]
