# Generated by Django 4.2.5 on 2023-09-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('path_url', models.CharField(max_length=255, unique=True)),
                ('info_title', models.CharField()),
                ('info_city', models.CharField()),
                ('info_address', models.CharField()),
                ('info_schedule', models.CharField()),
                ('info_phone', models.CharField()),
                ('info_description', models.TextField()),
                ('info_website_url', models.CharField()),
                ('action_website_url', models.CharField()),
                ('action_title', models.CharField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_logo', models.BooleanField(default=False)),
                ('sort', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteExternalUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_service', models.CharField(choices=[('CUSTOM', 'Custom'), ('VK', 'Vk'), ('OK', 'Ok'), ('X', 'X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('VIMEO', 'Vimeo'), ('RUTUBE', 'Rutube')], default='CUSTOM', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website')),
            ],
        ),
    ]
