# Generated by Django 5.0.4 on 2024-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_visible_0',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать с 0 звезд?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_visible_1',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать с 1 звездой?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_visible_2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать с 2 звездами?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_visible_3',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать с 3 звездами?'),
        ),
    ]
