# Generated by Django 4.2.5 on 2023-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='stat_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='stat_reviews_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
