# Generated by Django 4.2.5 on 2023-11-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_negative_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_positive_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='request_form_negative_head',
            field=models.TextField(default='Написать директору', verbose_name='Заголовок формы запроса отзыва (негатив)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='request_form_positive_head',
            field=models.TextField(default='Наградите нас отзывом', verbose_name='Заголовок формы запроса отзыва (позитив)'),
        ),
    ]
