# Generated by Django 5.0.2 on 2024-03-28 10:33

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[300, 300], upload_to='dashboard/%Y/%m/%d/', verbose_name='логотип'),
        ),
    ]
