# Generated by Django 5.0.2 on 2024-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reviews_gis_negative_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов 2Гис за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_negative_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов 2Гис за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_negative_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов 2Гис за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_negative_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов 2Гис за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_positive_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов 2Гис за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_positive_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов 2Гис за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_positive_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов 2Гис за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_positive_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов 2Гис за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_total_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов 2Гис за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_total_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов 2Гис за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_total_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов 2Гис за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_gis_total_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов 2Гис за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_negative_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Google за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_negative_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Google за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_negative_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Google за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_negative_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Google за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_positive_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Google за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_positive_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Google за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_positive_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Google за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_positive_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Google за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_total_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Google за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_total_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Google за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_total_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Google за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_google_total_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Google за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_negative_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Яндекс за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_negative_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Яндекс за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_negative_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Яндекс за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_negative_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Яндекс за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_positive_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Яндекс за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_positive_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Яндекс за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_positive_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Яндекс за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_positive_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Яндекс за год'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_total_month_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Яндекс за месяц'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_total_quarter_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Яндекс за квартал'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_total_week_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Яндекс за неделю'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_yandex_total_year_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество отзывов Яндекс за год'),
        ),
    ]
