# Generated by Django 5.0.2 on 2024-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.CharField(choices=[('STARTS', 'Старт'), ('REGULAR', 'Стандарт'), ('BUSINESS', 'Бизнес')], default='STARTS', verbose_name='Тариф'),
        ),
    ]
