# Generated by Django 4.2.5 on 2023-10-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeMessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='текст тега')),
            ],
            options={
                'verbose_name': 'тег негативного сообщения',
                'verbose_name_plural': 'теги негативного сообщения',
                'db_table': 'resources_negative_message_tag',
            },
        ),
        migrations.CreateModel(
            name='PositiveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('text', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
            ],
            options={
                'verbose_name': 'позитивный отзыв',
                'verbose_name_plural': 'позитивные отзывы',
                'db_table': 'feedback_positive_review',
            },
        ),
        migrations.CreateModel(
            name='NegativeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('text', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
            ],
            options={
                'verbose_name': 'негативный отзыв',
                'verbose_name_plural': 'негативные отзывы',
                'db_table': 'resources_negative_review',
            },
        ),
        migrations.CreateModel(
            name='NegativeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('phone', models.CharField(max_length=255, verbose_name='контактный телефон')),
                ('text', models.TextField(blank=True, verbose_name='текст сообщения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch', verbose_name='филиал')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company', verbose_name='сеть')),
                ('negative_message_tag', models.ManyToManyField(blank=True, to='resources.negativemessagetag', verbose_name='теги негативных сообщений')),
            ],
            options={
                'verbose_name': 'негативное сообщение',
                'verbose_name_plural': 'негативные сообщения',
                'db_table': 'resources_negative_message',
            },
        ),
    ]
