# Generated by Django 5.0.2 on 2024-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_company_address_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_now_parse',
            field=models.BooleanField(default=True, verbose_name='парсится сейчас?'),
        ),
    ]
