# Generated by Django 4.2.5 on 2023-11-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_company_total_negative_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('YANDEX', 'Яндекс'), ('GIS', '2Гис'), ('GOOGLE', 'Google')], default='YANDEX', verbose_name='сервис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('remote_id', models.CharField(blank=True, null=True, verbose_name='ID сервиса')),
                ('conversation_id', models.CharField(blank=True, null=True, verbose_name='ID диалога')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='рейтинг')),
                ('avatar_url', models.CharField(blank=True, null=True, verbose_name='url аватара')),
                ('name', models.CharField(verbose_name='пользователь')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company', verbose_name='сеть')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'resources_review',
            },
        ),
    ]
