# Generated by Django 4.2.5 on 2023-10-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_negativemessagetag_positivereview_negativereview_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='positivereview',
            table='resources_positive_review',
        ),
    ]
