# Generated by Django 5.0.4 on 2024-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_company_is_visible_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_billing',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_owner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='владелец?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.CharField(choices=[('START', 'Старт'), ('REGULAR', 'Стандарт'), ('BUSINESS', 'Бизнес')], default='START', null=True, verbose_name='Тариф'),
        ),
    ]
