# Generated by Django 4.2.5 on 2023-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_website_stat_reviews_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteExternalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_service', models.CharField(choices=[('CUSTOM', 'Custom'), ('YANDEX', 'Yandex'), ('GOOGLE', 'Google'), ('GIS', 'Gis')], default='CUSTOM', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField()),
            ],
        ),
    ]
