# Generated by Django 5.0.2 on 2024-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_company_reviews_gis_negative_month_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='form_contact_facebook',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_instagram',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_ok',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Одноклассники'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_telegram',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Telegram'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_viber',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Viber'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_vk',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка VK'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_website',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Вебсайт'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_whatsapp',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Whatsapp'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_x',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка X'),
        ),
        migrations.AddField(
            model_name='company',
            name='form_contact_youtube',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Youtube'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='телефон'),
        ),
    ]
