# Generated by Django 5.0.2 on 2024-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_company_is_now_parse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_now_parse',
            field=models.BooleanField(default=False, verbose_name='парсится сейчас?'),
        ),
    ]
