# Generated by Django 4.2.5 on 2023-11-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='from_bot',
            field=models.BooleanField(default=False, verbose_name='Отправлено ботом Портрет'),
        ),
    ]
