# Generated by Django 4.2.5 on 2023-10-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_positivereview_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='users',
        ),
    ]
