# Generated by Django 5.0.2 on 2024-03-25 15:54

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_company_form_contact_facebook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_notify_negative_portrate', models.BooleanField(default=True, verbose_name='оповещения Портрет')),
                ('can_notify_negative_yandex', models.BooleanField(default=True, verbose_name='оповещения Яндекс')),
                ('can_notify_negative_gis', models.BooleanField(default=True, verbose_name='оповещения 2Гис')),
                ('can_notify_negative_google', models.BooleanField(default=True, verbose_name='оповещения Google')),
                ('can_notify_at_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True, verbose_name='можно оповещать с')),
                ('can_notify_at_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True, verbose_name='можно оповещать до')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
                'db_table': 'resources_membership',
            },
        ),
    ]
