# Generated by Django 4.2.5 on 2023-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_review_from_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
        migrations.AlterField(
            model_name='notification',
            name='initiator',
            field=models.CharField(choices=[('PORTRATE_NEGATIVE_MESSAGE', 'Негативное сообщение Портрет'), ('YANDEX_NEGATIVE_REVIEW', 'Негативный отзыв Яндекс'), ('GIS_NEGATIVE_REVIEW', 'Негативный отзыв 2Гис'), ('GOOGLE_NEGATIVE_REVIEW', 'Негативный отзыв Google'), ('YANDEX_POSITIVE_REVIEW', 'Позитивный отзыв Яндекс'), ('GIS_POSITIVE_REVIEW', 'Позитивный отзыв 2Гис'), ('GOOGLE_POSITIVE_REVIEW', 'Позитивный отзыв Google'), ('YANDEX_PARSE_SUCCESS', 'Отзывы загружены Яндекс'), ('GIS_PARSE_SUCCESS', 'Отзывы загружены 2Гис'), ('GOOGLE_PARSE_SUCCESS', 'Отзывы загружены Google'), ('YANDEX_PARSE_ERROR', 'Ошибка загрузки Яндекс'), ('GIS_PARSE_ERROR', 'Ошибка загрузки 2Гис'), ('GOOGLE_PARSE_ERROR', 'Ошибка загрузки Google')], default='PORTRATE_NEGATIVE_MESSAGE', verbose_name='инициатор'),
        ),
    ]
