# Generated by Django 5.0.2 on 2024-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_company_is_now_parse'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_dark',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='визитка темная тема'),
        ),
        migrations.AddField(
            model_name='company',
            name='business_light',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='визитка темная тема'),
        ),
        migrations.AddField(
            model_name='company',
            name='stick_dark',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='наклейка темная тема'),
        ),
        migrations.AddField(
            model_name='company',
            name='stick_light',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='наклейка светлая тема'),
        ),
    ]
