# Generated by Django 5.0.2 on 2024-03-25 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_membership_alter_company_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_notify_at_from_stars',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='количество звезд для оповещений'),
        )
    ]
