# Generated by Django 5.0.4 on 2024-08-21 09:13

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_profile_business_price_monthly_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='RUB', max_digits=14, null=True, verbose_name='баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_price_monthly_base',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('1500'), default_currency='RUB', max_digits=14, null=True, verbose_name='стоимость тарифа Бизнес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('Europe/Moscow', 'Москва'), ('Asia/Yekaterinburg', 'Екатеринбург')], default='UTC', null=True, verbose_name='временная зона по умолчанию'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.CharField(choices=[('START', 'Старт'), ('REGULAR', 'Стандарт'), ('BUSINESS', 'Бизнес')], default='START', null=True, verbose_name='тариф'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regular_price_monthly_base',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('500'), default_currency='RUB', max_digits=14, null=True, verbose_name='стоимость тарифа Стандарт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_price_monthly_base',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('250'), default_currency='RUB', max_digits=14, null=True, verbose_name='стоимость тарифа Старт'),
        ),
    ]
