# Generated by Django 4.2.5 on 2023-10-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_rename_user_company_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(choices=[('PORTRATE_NEGATIVE_MESSAGE', 'Негативное сообщение Портрет'), ('YANDEX_NEGATIVE_REVIEW', 'Негативный отзыв Яндекс'), ('GIS_NEGATIVE_REVIEW', 'Негативный отзыв 2Гис'), ('GOOGLE_NEGATIVE_REVIEW', 'Негативный отзыв Google'), ('YANDEX_POSITIVE_REVIEW', 'Позитивный отзыв Яндекс'), ('GIS_POSITIVE_REVIEW', 'Позитивный отзыв 2Гис'), ('GOOGLE_POSITIVE_REVIEW', 'Позитивный отзыв Google'), ('YANDEX_PARSE_SUCCESS', 'Отзывы загружены Яндекс'), ('GIS_PARSE_SUCCESS', 'Отзывы загружены 2Гис'), ('GOOGLE_PARSE_SUCCESS', 'Отзывы загружены Google'), ('YANDEX_PARSE_ERROR', 'Ошибка загрузки Яндекс'), ('GIS_PARSE_ERROR', 'Ошибка загрузки 2Гис'), ('GOOGLE_PARSE_ERROR', 'Ошибка загрузки Google')], default='PORTRATE_NEGATIVE_MESSAGE', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('text', models.TextField(verbose_name='текст оповещения')),
                ('url', models.CharField(blank=True, verbose_name='url оповещения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company', verbose_name='сеть')),
            ],
            options={
                'verbose_name': 'оповещение',
                'verbose_name_plural': 'оповещения',
                'db_table': 'resources_notification',
            },
        ),
    ]
