# Generated by Django 5.0.4 on 2024-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_company_business_dark_company_business_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Name', verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='remote_id',
            field=models.CharField(default='Remote_Id', verbose_name='ID (агрегация)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='количество звезд'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='Text', verbose_name='текст отзыва'),
            preserve_default=False,
        ),
    ]
