# Generated by Django 4.2.5 on 2023-09-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_websitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.website'),
            preserve_default=False,
        ),
    ]
