# Generated by Django 4.2.5 on 2023-10-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='negative_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.negativemessage', verbose_name='негативное сообщение'),
            preserve_default=False,
        ),
    ]
