# Generated by Django 4.2.5 on 2023-11-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_company_dikidi_negative_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dikidi_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Dikidi'),
        ),
        migrations.AddField(
            model_name='company',
            name='dikidi_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Dikidi'),
        ),
        migrations.AddField(
            model_name='company',
            name='flamp_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Flamp'),
        ),
        migrations.AddField(
            model_name='company',
            name='flamp_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Flamp'),
        ),
        migrations.AddField(
            model_name='company',
            name='gis_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга 2Гис'),
        ),
        migrations.AddField(
            model_name='company',
            name='gis_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов 2Гис'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Google'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Google'),
        ),
        migrations.AddField(
            model_name='company',
            name='irecommend_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Irecommend'),
        ),
        migrations.AddField(
            model_name='company',
            name='irecommend_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Irecommend'),
        ),
        migrations.AddField(
            model_name='company',
            name='mapsme_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Mapsme'),
        ),
        migrations.AddField(
            model_name='company',
            name='mapsme_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Mapsme'),
        ),
        migrations.AddField(
            model_name='company',
            name='otzovik_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Отзовик'),
        ),
        migrations.AddField(
            model_name='company',
            name='otzovik_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Отзовик'),
        ),
        migrations.AddField(
            model_name='company',
            name='prodoctorov_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Продокторов'),
        ),
        migrations.AddField(
            model_name='company',
            name='prodoctorov_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Продокторов'),
        ),
        migrations.AddField(
            model_name='company',
            name='restoclub_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Рестоклуб'),
        ),
        migrations.AddField(
            model_name='company',
            name='restoclub_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Рестоклуб'),
        ),
        migrations.AddField(
            model_name='company',
            name='tripadvisor_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Tripadvisor'),
        ),
        migrations.AddField(
            model_name='company',
            name='tripadvisor_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Tripadvisor'),
        ),
        migrations.AddField(
            model_name='company',
            name='yandex_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Яндекс'),
        ),
        migrations.AddField(
            model_name='company',
            name='yandex_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Яндекс'),
        ),
        migrations.AddField(
            model_name='company',
            name='zoon_rate_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки рейтинга Zoon'),
        ),
        migrations.AddField(
            model_name='company',
            name='zoon_reviews_last_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последней загрузки отзывов Zoon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dikidi_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Dikidi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dikidi_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Dikidi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dikidi_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Dikidi'),
        ),
        migrations.AlterField(
            model_name='company',
            name='flamp_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Flamp'),
        ),
        migrations.AlterField(
            model_name='company',
            name='flamp_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Flamp'),
        ),
        migrations.AlterField(
            model_name='company',
            name='flamp_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Flamp'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gis_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов 2Гис'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gis_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов 2Гис'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gis_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг 2Гис'),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Google'),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Google'),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Google'),
        ),
        migrations.AlterField(
            model_name='company',
            name='irecommend_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Irecommend'),
        ),
        migrations.AlterField(
            model_name='company',
            name='irecommend_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Irecommend'),
        ),
        migrations.AlterField(
            model_name='company',
            name='irecommend_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Irecommend'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mapsme_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Mapsme'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mapsme_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Mapsme'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mapsme_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Mapsme'),
        ),
        migrations.AlterField(
            model_name='company',
            name='otzovik_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Отзовик'),
        ),
        migrations.AlterField(
            model_name='company',
            name='otzovik_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Отзовик'),
        ),
        migrations.AlterField(
            model_name='company',
            name='otzovik_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Отзовик'),
        ),
        migrations.AlterField(
            model_name='company',
            name='portrate_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Портрет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='portrate_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Портрет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='prodoctorov_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Продокторов'),
        ),
        migrations.AlterField(
            model_name='company',
            name='prodoctorov_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Продокторов'),
        ),
        migrations.AlterField(
            model_name='company',
            name='prodoctorov_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Продокторов'),
        ),
        migrations.AlterField(
            model_name='company',
            name='restoclub_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Рестоклуб'),
        ),
        migrations.AlterField(
            model_name='company',
            name='restoclub_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Рестоклуб'),
        ),
        migrations.AlterField(
            model_name='company',
            name='restoclub_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Рестоклуб'),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов всего'),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов всего'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tripadvisor_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Tripadvisor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tripadvisor_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Tripadvisor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tripadvisor_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Tripadvisor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='yandex_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Яндекс'),
        ),
        migrations.AlterField(
            model_name='company',
            name='yandex_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Яндекс'),
        ),
        migrations.AlterField(
            model_name='company',
            name='yandex_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Яндекс'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zoon_negative_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество негативных отзывов Zoon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zoon_positive_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество позитивных отзывов Zoon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zoon_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='рейтинг Zoon'),
        ),
    ]
