# Generated by Django 5.0.4 on 2024-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_profile_business_max_count_profile_regular_max_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_max_count',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='максимальное количество филиалов тарифа Бизнес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regular_max_count',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='максимальное количество филиалов тарифа Стандарт'),
        ),
    ]
