# Generated by Django 4.2.5 on 2023-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resources', '0006_websitepage_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'филиал', 'verbose_name_plural': 'филиалы'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Вебсайт', 'verbose_name_plural': 'Вебсайты'},
        ),
        migrations.AddField(
            model_name='website',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='website',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.branch', verbose_name='филиал'),
        ),
    ]
