# Generated by Django 5.0.4 on 2024-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_review_name_alter_review_remote_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
    ]
