# Generated by Django 4.2.5 on 2023-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_company_dikidi_rate_last_parse_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='yandex_rate_count',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='количество оценок Яндекс'),
        ),
        migrations.AddField(
            model_name='company',
            name='yandex_stars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, verbose_name='звезды Яндекс'),
        ),
    ]
