# Generated by Django 5.0.4 on 2024-04-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_company_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_now_parse',
        ),
    ]
