# Generated by Django 4.2.5 on 2023-09-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_branch_options_alter_website_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'вебсайт', 'verbose_name_plural': 'вебсайты'},
        ),
        migrations.AlterModelOptions(
            name='websiteimage',
            options={'verbose_name': 'изображение вебсайта', 'verbose_name_plural': 'изображения вебсайтов'},
        ),
        migrations.RemoveField(
            model_name='website',
            name='action_title',
        ),
        migrations.RemoveField(
            model_name='website',
            name='action_website_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_phone',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_website_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='stat_reviews_count',
        ),
        migrations.RemoveField(
            model_name='website',
            name='stat_reviews_rating',
        ),
    ]
