# Generated by Django 5.0.4 on 2024-08-22 08:15

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_profile_business_max_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('60'), default_currency='RUB', max_digits=14, null=True, verbose_name='баланс'),
        ),
    ]
