# Generated by Django 4.2.5 on 2023-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_company_yandex_rate_count_company_yandex_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='yandex_rate_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество оценок Яндекс'),
        ),
    ]
