# Generated by Django 4.2.5 on 2023-10-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_notification_negative_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='negative_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.negativemessage', verbose_name='негативное сообщение'),
        ),
    ]
