# Generated by Django 4.2.5 on 2023-09-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_website_options_alter_websiteimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CUSTOM', 'Custom'), ('YANDEX', 'Yandex'), ('GOOGLE', 'Google'), ('GIS', 'Gis'), ('MAPSME', 'Mapsme')], default='CUSTOM', verbose_name='значение')),
                ('title', models.CharField(blank=True, verbose_name='название')),
                ('value', models.CharField(verbose_name='ссылка на карточку')),
            ],
            options={
                'verbose_name': 'карточка вебсайта',
                'verbose_name_plural': 'карточки вебсайта',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CUSTOM', 'Custom'), ('PHONE', 'Phone'), ('WHATSAPP', 'Whatsapp'), ('TELEGRAM', 'Telegram'), ('VIBER', 'Viber'), ('EMAIL', 'Email')], default='CUSTOM', verbose_name='платформа')),
                ('title', models.CharField(blank=True, verbose_name='название')),
                ('value', models.CharField(verbose_name='значение')),
            ],
            options={
                'verbose_name': 'контакт вебсайта',
                'verbose_name_plural': 'контакты вебсайта',
            },
        ),
        migrations.CreateModel(
            name='WebsiteUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CUSTOM', 'Custom'), ('VK', 'Vk'), ('OK', 'Ok'), ('X', 'X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('VIMEO', 'Vimeo'), ('RUTUBE', 'Rutube')], default='CUSTOM', verbose_name='значение')),
                ('title', models.CharField(blank=True, verbose_name='название')),
                ('value', models.CharField(verbose_name='ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'ссылка вебсайта',
                'verbose_name_plural': 'ссылки вебсайта',
            },
        ),
        migrations.RemoveField(
            model_name='websiteexternalurl',
            name='website',
        ),
        migrations.AlterModelOptions(
            name='websiteimage',
            options={'verbose_name': 'изображение вебсайта', 'verbose_name_plural': 'изображения вебсайта'},
        ),
        migrations.AlterModelOptions(
            name='websitepage',
            options={'verbose_name': 'страница вебсайта', 'verbose_name_plural': 'страницы вебсайта'},
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_address',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_city',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_description',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_schedule',
        ),
        migrations.RemoveField(
            model_name='website',
            name='info_title',
        ),
        migrations.RemoveField(
            model_name='website',
            name='path_url',
        ),
        migrations.RemoveField(
            model_name='websiteimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='content',
        ),
        migrations.AddField(
            model_name='website',
            name='address',
            field=models.CharField(default=1, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='city',
            field=models.CharField(default=1, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='path',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='поддомен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='schedule',
            field=models.CharField(default=1, verbose_name='график работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(default=1, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteimage',
            name='file',
            field=models.ImageField(default=1, upload_to='website_images/%Y/%m/%d/', verbose_name='файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitepage',
            name='value',
            field=models.TextField(default=1, verbose_name='значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано?'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='is_logo',
            field=models.BooleanField(default=False, verbose_name='логотип?'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='title',
            field=models.CharField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='websiteimage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website', verbose_name='вебсайт'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='title',
            field=models.CharField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website', verbose_name='вебсайт'),
        ),
        migrations.DeleteModel(
            name='WebsiteExternalCard',
        ),
        migrations.DeleteModel(
            name='WebsiteExternalUrl',
        ),
        migrations.AddField(
            model_name='websiteurl',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website', verbose_name='вебсайт'),
        ),
        migrations.AddField(
            model_name='websitecontact',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website', verbose_name='вебсайт'),
        ),
        migrations.AddField(
            model_name='websitecard',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.website', verbose_name='вебсайт'),
        ),
    ]
