# Generated by Django 4.2.5 on 2023-11-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_company_yandex_rate_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='yandex_stars',
            new_name='yandex_rate_stars',
        ),
    ]
