# Generated by Django 4.2.5 on 2023-09-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_websitecard_websitecontact_websiteurl_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='websiteimage',
            table='website_images',
        ),
    ]
