# Generated by Django 5.0.4 on 2024-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
