# Generated by Django 4.2.5 on 2023-10-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_notification_negative_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='url оповещения'),
        ),
    ]
