# Generated by Django 4.2.5 on 2023-09-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_websiteimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='websiteimage',
            table='resources_website_images',
        ),
    ]
