# Generated by Django 5.0.4 on 2024-08-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.CharField(choices=[('ANNUALLY', 'Год'), ('MONTHLY', 'Месяц')], default='ANNUALLY', null=True, verbose_name='период'),
        ),
    ]
