# Generated by Django 5.0.4 on 2024-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID карты'),
        ),
    ]
