# Generated by Django 4.2.5 on 2023-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст отзыва'),
        ),
    ]
