# Generated by Django 4.2.5 on 2023-09-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_websiteimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='resources_branch',
        ),
        migrations.AlterModelTable(
            name='website',
            table='resources_website',
        ),
        migrations.AlterModelTable(
            name='websitecard',
            table='resources_website_card',
        ),
        migrations.AlterModelTable(
            name='websitecontact',
            table='resources_website_contact',
        ),
        migrations.AlterModelTable(
            name='websitepage',
            table='resources_website_page',
        ),
        migrations.AlterModelTable(
            name='websiteurl',
            table='resources_website_url',
        ),
    ]
