# Generated by Django 4.2.5 on 2023-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_review_answer_alter_review_name_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='remote_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID (агрегация)'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('company', 'remote_id')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='conversation_id',
        ),
    ]
