# Generated by Django 4.2.5 on 2023-09-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_alter_branch_table_alter_website_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='websitecard',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='websitecontact',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='websiteimage',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='websitepage',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='websiteurl',
            old_name='title',
            new_name='name',
        ),
    ]
