# Generated by Django 4.2.5 on 2023-09-24 19:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_rename_title_branch_name_rename_title_website_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='color_accent',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='цветовой акцент'),
        ),
        migrations.AlterField(
            model_name='websitecard',
            name='platform',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('YANDEX', 'Yandex'), ('GOOGLE', 'Google'), ('GIS', 'Gis'), ('MAPSME', 'Mapsme')], default='CUSTOM', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='websitecontact',
            name='platform',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('PHONE', 'Phone'), ('WHATSAPP', 'Whatsapp'), ('TELEGRAM', 'Telegram'), ('VIBER', 'Viber'), ('EMAIL', 'Email')], default='CUSTOM', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='websitecontact',
            name='value',
            field=models.CharField(verbose_name='контакт'),
        ),
        migrations.AlterField(
            model_name='websiteurl',
            name='platform',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('VK', 'Vk'), ('OK', 'Ok'), ('X', 'X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('VIMEO', 'Vimeo'), ('RUTUBE', 'Rutube')], default='CUSTOM', verbose_name='тип'),
        ),
    ]
