# Generated by Django 5.0.4 on 2024-09-16 11:03

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='активно?')),
                ('is_visible_master', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в мастере?')),
                ('is_visible_finance', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в тарифах?')),
                ('is_visible_profile', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в профиле?')),
                ('is_visible_home', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в списке филиалов?')),
                ('is_visible_statistic', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в статистике?')),
                ('is_visible_reviews', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в отзывах?')),
                ('is_visible_messages', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в жалобах?')),
                ('is_visible_widget', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в виджете?')),
                ('is_visible_feedback', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в визитке?')),
                ('is_visible_qr', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в списке qr?')),
                ('is_visible_notifications', models.BooleanField(blank=True, default=False, null=True, verbose_name='отображать в уведомлениях?')),
                ('name', models.CharField(blank=True, null=True, verbose_name='название')),
                ('preview', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=1, size=[256, 256], upload_to='dashboard/%Y/%m/%d/', verbose_name='превью')),
                ('media', models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='медиа файл')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company', verbose_name='филиал')),
            ],
            options={
                'verbose_name': 'история',
                'verbose_name_plural': 'истории',
                'db_table': 'resources_story',
            },
        ),
    ]
