# Generated by Django 4.2.5 on 2023-09-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_website_color_accent_alter_websitecard_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='color_accent',
        ),
    ]
