# Generated by Django 5.0.4 on 2024-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='api_secret',
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name='№ заказа'),
        ),
    ]
