# Generated by Django 4.2.5 on 2024-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0015_notification_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateField(verbose_name="дата создания"),
        ),
    ]
