# Generated by Django 4.2.5 on 2023-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_remove_website_color_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='specialization',
            field=models.CharField(default=1, verbose_name='Специализация'),
            preserve_default=False,
        ),
    ]
