# Generated by Django 5.0.4 on 2024-09-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_story_users_alter_review_remote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='company',
        ),
    ]
