# Generated by Django 4.2.5 on 2023-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_website_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='schedule',
        ),
        migrations.AddField(
            model_name='website',
            name='friday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в пятницу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_friday',
            field=models.BooleanField(default=True, verbose_name='работает в пятницу?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_monday',
            field=models.BooleanField(default=True, verbose_name='работает в понедельник?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_saturday',
            field=models.BooleanField(default=True, verbose_name='работает в субботу?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_sunday',
            field=models.BooleanField(default=True, verbose_name='работает в воскресенье?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_thursday',
            field=models.BooleanField(default=True, verbose_name='работает в четверг?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_tuesday',
            field=models.BooleanField(default=True, verbose_name='работает в вторник?'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_work_at_wednesday',
            field=models.BooleanField(default=True, verbose_name='работает в среду?'),
        ),
        migrations.AddField(
            model_name='website',
            name='monday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в понедельник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='saturday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в субботу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='sunday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в воскресенье'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='thursday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в четверг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='tuesday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы во вторник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='wednesday_schedule',
            field=models.CharField(default=1, verbose_name='часы работы в среду'),
            preserve_default=False,
        ),
    ]
