# Generated by Django 4.2.5 on 2023-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_remove_website_schedule_website_friday_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteurl',
            name='platform',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('WEBSITE', 'Website'), ('VK', 'Vk'), ('OK', 'Ok'), ('X', 'X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('RUTUBE', 'Rutube')], default='CUSTOM', verbose_name='тип'),
        ),
    ]
