# Generated by Django 5.0.1 on 2024-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_company_gis_rate_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='flamp_id',
            new_name='flamp_parser_link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dikidi_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gis_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='irecommend_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mapsme_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='otzovik_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='prodoctorov_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='restoclub_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tripadvisor_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='yandex_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zoon_id',
        ),
        migrations.AddField(
            model_name='company',
            name='dikidi_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Dikidi'),
        ),
        migrations.AddField(
            model_name='company',
            name='gis_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами 2Гис'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Google'),
        ),
        migrations.AddField(
            model_name='company',
            name='irecommend_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Irecommend'),
        ),
        migrations.AddField(
            model_name='company',
            name='mapsme_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Mapsme'),
        ),
        migrations.AddField(
            model_name='company',
            name='otzovik_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Отзовик'),
        ),
        migrations.AddField(
            model_name='company',
            name='prodoctorov_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Продокторов'),
        ),
        migrations.AddField(
            model_name='company',
            name='restoclub_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Рестоклуб'),
        ),
        migrations.AddField(
            model_name='company',
            name='tripadvisor_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Tripadvisor'),
        ),
        migrations.AddField(
            model_name='company',
            name='yandex_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Яндекс'),
        ),
        migrations.AddField(
            model_name='company',
            name='zoon_parser_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на страницу с отзывами Zoon'),
        ),
    ]
