# Generated by Django 4.2.5 on 2023-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_websiteurl_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='action_button_text',
            field=models.TextField(default="Записаться",
                                   verbose_name='текст кнопки действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='action_button_url',
            field=models.TextField(default="/",
                                   verbose_name='url кнопки действия'),
            preserve_default=False,
        ),
    ]
