# Generated by Django 5.0.1 on 2024-02-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_rename_flamp_id_company_flamp_parser_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gis_rate_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='gis_rate_stars',
        ),
        migrations.RemoveField(
            model_name='company',
            name='yandex_rate_count',
        ),
        migrations.RemoveField(
            model_name='company',
            name='yandex_rate_stars',
        ),
    ]
