# Generated by Django 5.0.1 on 2024-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_remove_company_gis_rate_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='from_bot',
        ),
    ]
