# Generated by Django 4.2.5 on 2023-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_website_action_button_text_website_action_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='action_button_text',
            field=models.CharField(verbose_name='текст кнопки действия'),
        ),
        migrations.AlterField(
            model_name='website',
            name='action_button_url',
            field=models.CharField(verbose_name='url кнопки действия'),
        ),
    ]
