# Generated by Django 5.0.4 on 2024-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_remove_story_is_video_alter_story_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='избражение'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_video',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='видео?'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='видео'),
        ),
    ]
