# Generated by Django 5.0.1 on 2024-02-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_remove_review_answer_remove_review_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='скрыть в виджете'),
        ),
    ]
