# Generated by Django 4.2.5 on 2023-10-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_alter_website_action_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.branch', verbose_name='филиал'),
        ),
    ]
