# Generated by Django 4.2.5 on 2023-10-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_alter_website_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecard',
            name='platform',
            field=models.CharField(choices=[('CUSTOM', 'Custom'), ('YANDEX', 'Yandex'), ('GOOGLE', 'Google'), ('GIS', 'Gis'), ('MAPSME', 'Mapsme'), ('DIKIDI', 'Dikidi'), ('RESTOCLUB', 'Restoclub'), ('TRIPADVISOR', 'Tripadvisor'), ('PRODOCTOROV', 'Prodoctorov'), ('FLAMP', 'Flamp'), ('ZOON', 'Zoon'), ('OTZOVIK', 'Otzovik'), ('IRECOMMEND', 'Irecommend')], default='CUSTOM', verbose_name='тип'),
        ),
    ]
