# Generated by Django 5.0.1 on 2024-02-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='request_form_home_success_head',
            field=models.TextField(default='Ваша претенизия успешно отправлена', verbose_name='Заголовок формы запроса отзыва (резулита отправки негатива)'),
        ),
        migrations.AddField(
            model_name='company',
            name='request_form_home_success_text',
            field=models.TextField(default='В близжайшее время с вами свяжется администратор', verbose_name='Текст формы запроса отзыва (резулита отправки негатива)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='скрыто в виджете'),
        ),
    ]
