# Generated by Django 5.0.1 on 2024-02-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_company_request_form_home_success_head_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='request_form_home_success_head',
            new_name='request_form_success_head',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='request_form_home_success_text',
            new_name='request_form_success_text',
        ),
    ]
