# Generated by Django 4.2.5 on 2023-10-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_alter_websitecard_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='api_secret',
            field=models.CharField(default='U60VsdDc', verbose_name='API ключ'),
        ),
    ]
