# Generated by Django 5.0.1 on 2024-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_rename_request_form_home_success_head_company_request_form_success_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='request_form_success_head',
            field=models.TextField(default='Ваша успешно отправлена', verbose_name='Заголовок формы запроса отзыва (резулита отправки негатива)'),
        ),
    ]
