# Generated by Django 4.2.5 on 2023-10-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_branch_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='api_secret',
            field=models.CharField(default='tHaeYYMn', unique=True, verbose_name='API ключ'),
        ),
    ]
