# Generated by Django 5.0.4 on 2024-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_alter_clickstamp_created_at_alter_clickstamp_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='count_avito',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Авито'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_flamp',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Flamp'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_gis',
            field=models.IntegerField(default=0, verbose_name='количество отзывов 2Гис'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_google',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Google'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_irecommend',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Irecommend'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_otzovik',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Отзовик'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_prodoctorov',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Продокторов'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_tripadvisor',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Tripadvisor'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_yandex',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Яндекс'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_yandex_services',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Яндекс услуги'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_yell',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Yell'),
        ),
        migrations.AddField(
            model_name='company',
            name='count_zoon',
            field=models.IntegerField(default=0, verbose_name='количество отзывов Zoon'),
        ),
    ]
