# Generated by Django 5.0.4 on 2024-10-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_company_count_avito_company_count_flamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='count_avito',
            new_name='reviews_count_remote_avito',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_flamp',
            new_name='reviews_count_remote_flamp',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_gis',
            new_name='reviews_count_remote_gis',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_google',
            new_name='reviews_count_remote_google',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_irecommend',
            new_name='reviews_count_remote_irecommend',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_otzovik',
            new_name='reviews_count_remote_otzovik',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_prodoctorov',
            new_name='reviews_count_remote_prodoctorov',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_tripadvisor',
            new_name='reviews_count_remote_tripadvisor',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_yandex',
            new_name='reviews_count_remote_yandex',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_yandex_services',
            new_name='reviews_count_remote_yandex_services',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_yell',
            new_name='reviews_count_remote_yell',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='count_zoon',
            new_name='reviews_count_remote_zoon',
        ),
    ]
