# Generated by Django 5.0.1 on 2024-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_alter_company_request_form_success_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='request_form_success_head',
            field=models.TextField(default='Ваша претензия отправлена', verbose_name='Заголовок формы запроса отзыва (резулита отправки негатива)'),
        ),
    ]
