# Generated by Django 5.0.1 on 2024-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_alter_company_request_form_success_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_secret',
            field=models.CharField(blank=True, null=True, verbose_name='API ключ'),
        ),
    ]
