# Generated by Django 4.2.5 on 2023-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_alter_branch_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='api_secret',
            field=models.CharField(default='3BeW5gnn', unique=True, verbose_name='API ключ'),
        ),
    ]
