# Generated by Django 5.0.1 on 2024-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_company_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api_secret',
            field=models.CharField(db_index=True, verbose_name='API ключ'),
        ),
    ]
