# Generated by Django 4.2.5 on 2023-10-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_alter_branch_api_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='api_secret',
            field=models.CharField(default='FRxo2MIT', unique=True, verbose_name='API ключ'),
        ),
    ]
