# Generated by Django 5.0.4 on 2024-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_company_feedback_text_create_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='feedback_text_request_heading',
            field=models.CharField(default='Наградите нас отзывом', verbose_name='заголовок страницы запрос отзывов'),
        ),
    ]
