# Generated by Django 5.0.4 on 2024-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_alter_company_feedback_text_request_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='feedback_text_request_heading',
            field=models.CharField(default='Наградите нас отзывом', verbose_name='заголовок страницы запроса отзывов'),
        ),
    ]
