# Generated by Django 5.0.4 on 2024-10-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_alter_company_feedback_text_request_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='video',
        ),
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='видео')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/', verbose_name='изображение')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.story', verbose_name='история')),
            ],
            options={
                'verbose_name': 'медиа история',
                'verbose_name_plural': 'медиа историй',
                'db_table': 'resources_story_media',
            },
        ),
    ]
