# Generated by Django 5.0.2 on 2024-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_rating_rename_negativemessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parser_link_gis',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка 2Гис'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parser_link_google',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Google'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parser_link_yandex',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Яндекс'),
        ),
    ]
