# Generated by Django 5.0.4 on 2024-10-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_remove_story_image_remove_story_video_storyslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyslide',
            options={'verbose_name': 'медиа истории', 'verbose_name_plural': 'медиа историй'},
        ),
    ]
