# Generated by Django 5.0.2 on 2024-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_alter_message_options_company_messages_total_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_first_parsing',
            field=models.BooleanField(default=True, verbose_name='первый парсинг?'),
        ),
    ]
