# Generated by Django 5.0.4 on 2024-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_alter_storyslide_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyslide',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='порядок'),
            preserve_default=False,
        ),
    ]
