# Generated by Django 5.0.2 on 2024-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_company_is_first_parsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_cache',
            field=models.JSONField(blank=True, null=True, verbose_name='Кеш пользователей'),
        ),
    ]
