# Generated by Django 5.0.2 on 2024-03-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_company_user_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='form_link_flamp',
            field=models.CharField(blank=True, null=True, verbose_name='ссылка Flamp'),
        ),
    ]
