# Generated by Django 5.0.4 on 2024-10-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_alter_storyslide_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='is_visible_profile',
            new_name='is_visible_user',
        ),
    ]
