# Generated by Django 5.0.2 on 2024-03-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0034_company_form_link_flamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_cache',
        ),
    ]
