# Generated by Django 5.0.4 on 2024-11-24 18:39

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0035_instruction_alter_storyslide_table_instructionslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='preview',
        ),
        migrations.AddField(
            model_name='instructionslide',
            name='preview',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[256, 256], upload_to='dashboard/%Y/%m/%d/', verbose_name='превью'),
            preserve_default=False,
        ),
    ]
