# Generated by Django 5.0.2 on 2024-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0035_remove_company_user_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='отображается в виджете'),
        ),
    ]
