# Generated by Django 5.0.2 on 2024-03-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_remove_review_is_hidden_review_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
