# Generated by Django 5.0.4 on 2024-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_remove_instruction_preview_instructionslide_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionslide',
            name='preview',
        ),
        migrations.AddField(
            model_name='instruction',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
            preserve_default=False,
        ),
    ]
