# Generated by Django 5.0.2 on 2024-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0037_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_gis',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг 2Гис'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_google',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг Google'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_yandex',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг Яндекс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
