# Generated by Django 5.0.4 on 2024-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0037_remove_instructionslide_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='description',
        ),
        migrations.AddField(
            model_name='instructionslide',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
            preserve_default=False,
        ),
    ]
