# Generated by Django 5.0.4 on 2024-11-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_remove_instruction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionslide',
            name='image',
            field=models.ImageField(default='', upload_to='dashboard/%Y/%m/%d/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
