# Generated by Django 5.0.2 on 2024-03-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_alter_rating_created_at_alter_rating_rating_gis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('rating_yandex', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг Яндекс')),
                ('rating_gis', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг 2Гис')),
                ('rating_google', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='рейтинг Google')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Рейтинг компании',
                'verbose_name_plural': 'Рейтинги компании',
                'db_table': 'resources_company_rate_stamp',
                'unique_together': {('company', 'created_at')},
            },
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
