name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ID_RSA_DOCKER_1: ${{ secrets.ID_RSA_DOCKER_1 }}
      ID_RSA_PUB_DOCKER_1: ${{ secrets.ID_RSA_PUB_DOCKER_1 }}
      TEST_VAR: "HELLO"
    steps:
    - name: Configure ssh
      run: |
        mkdir -p ~/.ssh/
        echo $ID_RSA_DOCKER_1 > ~/.ssh/id_rsa
        echo $ID_RSA_PUB_DOCKER_1 > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
        cat >>~/.ssh/config <<END
        Host docker_1
          HostName 45.86.180.236
          User root
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END
    - name: Cat_0 
      run: echo $ID_RSA_DOCKER_1
    - name: Cat_1 
      run: cat ~/.ssh/id_rsa
    - name: Cat_2 
      run: cat ~/.ssh/id_rsa.pub
